name: Containers

on:
  push:
    branches: [ master, devops ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Login to docker
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

    - name: Build the docker-compose stack
      run: |
        cp .env .env.prod
        docker-compose -f docker-compose.prod.yml --env-file .env.prod pull --ignore-pull-failures
        docker-compose -f docker-compose.prod.yml --env-file .env.prod build

    - name: Run the docker-compose step
      run: docker-compose -f docker-compose.prod.yml --env-file .env.prod up -d

    - name: Check running containers
      run: docker ps -a

    - name: Publish images
      if: github.ref == 'refs/heads/master'
      run: docker-compose -f docker-compose.prod.yml --env-file .env.prod push
